Repository IGSPK/casper-lms-server, pull requests merged in 2022-09, with the labels that each got.

#22 feat: file storage support implemented
  casper-lms-server.zip
  package-lock.json
  package.json
  src/app.module.ts
  src/controllers/account.controller.ts
  src/controllers/app.controller.ts
  src/controllers/course.controller.ts
  src/helpers/file.helper.ts
  src/main.ts
Labels: feature

#20 Feat/account
  dist.zip
  package-lock.json
  package.json
  src/_entities/course.entity.ts
  src/_entities/localFile.entity.ts
  src/_entities/user.entity.ts
  src/_stratigies/jwt.strategy.ts
  src/account/account.controller.ts
  src/account/account.module.ts
  src/admin/admin.controller.ts
  src/admin/admin.module.ts
  src/app.module.ts
  src/main.ts
  uploadedFiles/avatars/7e683a1b4e82a23e9f33c259e12c1bd2
  uploadedFiles/avatars/da0265c9b90f05a4316c91c2c131e351
Labels: feature

#26 feat: login complete
  src/account/account.controller.ts
Labels: feature, enhnacement

#27 fix: database configration updated
  .env
  src/config/database.config.ts
Labels: feature

#29 feat: account completed
  .env
  .gitignore
  package-lock.json
  package.json
  src/account/account.controller.ts
Labels: enhnacement

#30 feat: env static path is set
  .env
  src/config/filesystem.config.ts
  src/helpers/file.helper.ts
Labels: enhnacement

#32 feat: add course and get courses
  .env
  package.json
  public/thumbnails/1664015450612.jpeg
  public/thumbnails/1664021858710.jpeg
  public/thumbnails/1664022177111.jpeg
  public/thumbnails/1664023488422.jpeg
  public/thumbnails/1664196546070.jpeg
  public/thumbnails/1664196625233.jpeg
  public/thumbnails/1664196836291.jpeg
  public/thumbnails/1664198163827.jpeg
  public/thumbnails/1664199549892.jpeg
  src/_entities/course.entity.ts
  src/_entities/user.entity.ts
  src/account/account.controller.ts
  src/admin/admin.controller.ts
  src/admin/course.controller.ts
Labels: feature

#34 feat: add lecture and add short video
  public/thumbnails/1664196546070.jpeg
  public/thumbnails/1664196625233.jpeg
  public/thumbnails/1664198163827.jpeg
  public/thumbnails/1664199549892.jpeg
  public/thumbnails/1664282480841.jpeg
  public/thumbnails/1664283125385.jpeg
  public/videos/1664343441996.mp4
  public/videos/1664343501097.mp4
  src/_entities/course.entity.ts
  src/_entities/lecture.entity.ts
  src/_entities/video.entity.ts
  src/admin/admin.module.ts
  src/admin/course.controller.ts
  src/config/database.config.ts
  src/helpers/file.helper.ts
Labels: feature

#42 feat: subscription created
  package-lock.json
  package.json
  src/_entities/lecture.entity.ts
  src/_entities/subscription.entity.ts
  src/_entities/user.entity.ts
  src/_entities/video.entity.ts
  src/_stratigies/jwt.strategy.ts
  src/account/account.controller.ts
  src/account/account.module.ts
  src/admin/admin.controller.ts
  src/admin/admin.module.ts
  src/admin/course.controller.ts
  src/admin/subscription.controller.ts
  src/app.module.ts
  src/config/database.config.ts
Labels: feature
